### ISSUE TITLE
DAG generates for each letter of table

### ISSUE THREAD

**Issue by chandran-git** [Cloud-Innovation-Partners/miniBRS#60]
When we configure the table name in "" instead of [""] then it generates DAG for each latter of table.

**Comment by shahbaz-ali** [comment]
Thanks, @chandran-git for raising this issue. I think we have already stated in the docs the nature of `table` attribute in `config` variable. `table` attribute is expected to be an array entry rather than a string literal. https://minibrs.readthedocs.io/en/latest/settings/#variables

But, yes we shall validate the user value and try to avoid dag generation in case the value is not array type. I think raising an `InvalidTableName` exception will suffice the need. With this user will see the warning message on the GUI with the message speaking the reason for the error.
